@startuml VPC
'Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
'SPDX-License-Identifier: MIT (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/master/LICENSE)

' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Compute/EC2.puml
!include AWSPuml/Compute/EC2Instance.puml
!include AWSPuml/Database/RDS.puml
!include AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingApplicationLoadBalancer.puml

!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Groups/VPC.puml
!include AWSPuml/Groups/AvailabilityZone.puml
!include AWSPuml/Groups/PublicSubnet.puml
!include AWSPuml/Groups/PrivateSubnet.puml
!include AWSPuml/NetworkingContentDelivery/VPCNATGateway.puml
!include AWSPuml/NetworkingContentDelivery/VPCInternetGateway.puml

hide stereotype
skinparam linetype ortho

AWSCloudGroup(cloud) {
  VPCGroup(vpc) {
    AvailabilityZoneGroup(az_1, "\tAvailability Zone 1\t") {

      PrivateSubnetGroup(az_1_private_1, "Private subnet a1") {
        EC2Instance(az_1_ec2_1, "Instance", "") #Transparent
      }

      PrivateSubnetGroup(az_1_private_2, "Private subnet a2") {
       RDS(rds_master, "RDS Master", "db.t3.medium")
       RDS(rds_read_replica, "RDS Read Replica", "db.t3.medium")
       rds_read_replica <.> rds_master
      }

        rds_read_replica <--> az_1_ec2_1
    }

    AvailabilityZoneGroup(az_2, "\tAvailability Zone 2\t") {
      PrivateSubnetGroup(az_2_private_1, "Private subnet c1") {
        EC2Instance(az_2_ec2_1, "Instance", "") #Transparent
      }
      PrivateSubnetGroup(az_2_private_2, "Private subnet c2") {
        RDS(rds_standby, "RDS Standby", "db.t3.medium")
      }
    }

    rds_read_replica <-> az_2_ec2_1

  }
}
@enduml
