@startuml VPC
'Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
'SPDX-License-Identifier: MIT (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/master/LICENSE)

' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Compute/EC2.puml
!include AWSPuml/Compute/EC2Instance.puml
!include AWSPuml/Database/RDS.puml
!include AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingApplicationLoadBalancer.puml

!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Groups/VPC.puml
!include AWSPuml/Groups/AvailabilityZone.puml
!include AWSPuml/Groups/PublicSubnet.puml
!include AWSPuml/Groups/PrivateSubnet.puml
!include AWSPuml/NetworkingContentDelivery/VPCNATGateway.puml
!include AWSPuml/NetworkingContentDelivery/VPCInternetGateway.puml

hide stereotype
skinparam linetype ortho

AWSCloudGroup(cloud) {
  VPCGroup(vpc) {
    VPCInternetGateway(internet_gateway, "Internet gateway", "")

    ElasticLoadBalancingApplicationLoadBalancer(alb, "Application Load Balancer", "") #Transparent

    AvailabilityZoneGroup(az_1, "\tAvailability Zone 1\t") {

      PublicSubnetGroup(az_1_public, "Public subnet a1") {
        VPCNATGateway(az_1_nat_gateway, "NAT gateway", "") #Transparent
      }
      PrivateSubnetGroup(az_1_private_1, "Private subnet a1") {
        EC2Instance(az_1_ec2_1, "Instance", "") #Transparent
      }
      PrivateSubnetGroup(az_1_private_2, "Private subnet a2") {
       RDS(rds_master, "RDS Master", "db.t3.medium")
       RDS(rds_read_replica, "RDS Read Replica", "db.t3.medium")
       rds_read_replica <.> rds_master
      }

        az_1_ec2_1 ..> az_1_nat_gateway
        az_1_bastion <-> internet_gateway : "Connection to Internet Gateway"
        az_1_ec2_1 <--> az_1_bastion
        rds_read_replica <.u.> az_1_ec2_1
    }

    AvailabilityZoneGroup(az_2, "\tAvailability Zone 2\t") {
      PublicSubnetGroup(az_2_public, "Public subnet c1") {
        VPCNATGateway(az_2_nat_gateway, "NAT gateway", "") #Transparent
      }
      PrivateSubnetGroup(az_2_private_1, "Private subnet c1") {
        EC2Instance(az_2_ec2_1, "Instance", "") #Transparent
      }
      PrivateSubnetGroup(az_2_private_2, "Private subnet c2") {
        RDS(rds_standby, "RDS Standby", "db.t3.medium")
      }

        az_2_ec2_1 ..> az_2_nat_gateway
        az_2_bastion <-> internet_gateway : "Connection to Internet Gateway"
        az_2_ec2_1 <--> az_2_bastion
    }

    az_2_nat_gateway ..> internet_gateway
    az_1_nat_gateway ..> internet_gateway

    az_1_ec2_1 <--> alb : "Load Balanced Traffic"
    az_2_ec2_1 <--> alb : "Load Balanced Traffic"
    alb <--> internet_gateway : "Outgoing Traffic"

  }
}
@enduml
